### ISSUE TITLE
Allow `up.hello` and `up.destroy` to accept a NodeList

### ISSUE THREAD

**Issue by makmic** [unpoly/unpoly#140]
Hi there!

During an upgrade from Unpoly 0.56.6 to 0.62.1 I had to find out that the library silently dropped support for [NodeLists](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) when given to `up.hello` and `up.destroy`. This might especially be an issue for users migrating from jQuery to JS-compilers.

### JS example
```javascript
const parser = new DOMParser();
const dom = '<h1>foo</h1> <h2>bar</h2>';
const doc = parser.parseFromString(dom, "text/html");
up.hello(doc.body.childNodes)

> "Uncaught TypeError: e[n] is not a function
```

### JQuery example
```javascript
up.hello($('<h1>foo</h1> <h2>bar</h2>'))

> "UP] up.element.get(): Cannot cast multiple elements (E.fn.init(2) [h1, h2]) to a single element"
```
A real-world scenario would be, if the DOMString is a parsed server response of an AJAX call. **Both examples used to work in 0.56.6.**

### Workaround
I found myself including loops like this to emulate `up.hello(LIST)`:

```coffeescript
      for $newContent in $content
        if $newContent.nodeType != Node.TEXT_NODE
          up.hello($newContent)
```

### Feature request
Please consider (re-)introducing support for array-like arguments of `up.hello` and `up.destroy`.

Thanks!

**Comment by triskweline** [comment]
Hi @makmic!

Actually `up.hello()` and `up.destroy()` were never designed or documented to work with multiple elements. I was surprised to read that it worked in your app. I suppose jQuery internally iterated over elements and so it just happened to work.

Unfortunately I have decided against supporting automatic iteration for these functions. It would be inconsistent with the hundreds of other functions in the API that don't iterate either. Also when a function has a return value, a callback or resolves asynchronously, we would always need to think about what that would mean for an array-like argument.

> Workaround

I don't know if that helps, but you won't need to exclude text nodes if you access `children` instead of `childNodes`:

```javascript
const doc = parser.parseFromString(dom, "text/html");
up.util.each(doc.children, up.hello)
```

**Comment by makmic** [comment]
Hi @triskweline,

I see your point and agree that it would (re-)introduce some inconsistency that was never intended documented. It's probably better to just iterate over those nodes :-)
