### ISSUE TITLE
Ajax Headers possibly broken in 0.50.0

### ISSUE THREAD

**Issue by seanculver** [unpoly/unpoly#43]
First off, fantastic library, I'm really enjoying using unpoly and has helped save tons of time in my project.

I upgraded from 0.37.0 to 0.50.0 and my AJAX requests stopped working, specifically I'm getting a CSRF token invalid when I upgrade.
```javascript
var csrf = document.querySelector("meta[name=csrf-token]").content

up.ajax('pathtomyaction', {
  headers: {
    "x-csrf-token": csrf
  },
   method: 'PATCH',
   data: {
     // data
   }
})
```

Do I need to change the way I'm passing headers in 0.50.0?

**Comment by seanculver** [comment]
I now see the deprecation warnings. I'll try reimplementing in the new api. Thanks!

**Comment by triskweline** [comment]
Hm, even with the deprecated `up.ajax()` the code above should be OK.

What you might be seeing is a bug in 0.50.0 that fails to mark requests as AJAX request. This might confuse your server-side CSRF detection. Be sure to use 0.50.1.

Also by default all versions are automatically setting the CSRF token from `<meta name='csrf-token' value='secret-token'>`. You should not even have to configure it for every request. If your CSRF token lives somewhere else, you can configure a different source using the [`up.protocol.config.csrfToken`](https://unpoly.com/up.protocol.config#config.csrfToken) property.

**Comment by seanculver** [comment]
@triskweline I saw that you automatically add the csrf (note this works in Phoenix by default =)) in 0.50.1 when I did a diff against my version to see if I could see where the bug might be. Awesome change! 

I've upgraded to `0.50.1` now, one thing to note, I was getting a `.fail` is not a function error when I upgraded to `0.50.1` and used the `up.request` function but the documentation seems to still show that you can chain that callback.

**Comment by triskweline** [comment]
Sorry about the broken docs.

Instead of `.fail` you should use `.catch`, which is what standard promises use to register a rejection handler.
